name: Build and Deploy to Docker Hub

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Check Out Repo
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{vars.DOCKER_USERNAME}}
        password: ${{vars.DOCKER_SECRET}}

    - name: Build and Push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./docker/Dockerfile.user
        push: true
        tags: devindevil/user-app:latest 

    - name: Verify Pushed Image
      run: docker pull devindevil/user-app:latest 
    

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ vars.SSH_HOST }}
        username: ${{ vars.SSH_USERNAME }}
        key: ${{ vars.SSH_KEY }}
        script: |
          sudo docker pull devindevil/user-app:latest
          sudo docker stop user-app || true
          sudo docker rm user-app || true
          sudo docker run -d --name user-app -p 3005:3000 devindevil/user-app:latest